/// Flutter icons OVCIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  OVCIcons
///      fonts:
///       - asset: fonts/OVCIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class OVCIcons {
  OVCIcons._();

  static const _kFontFam = 'OVCIcons';

  static const IconData pickupicon = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData profileicon = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData addicon = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData forwardicon = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData backicon = IconData(0xe809, fontFamily: _kFontFam);
}